"""replace_requested_days_with_new_deadline

Revision ID: 1df6833f3ea3
Revises: f51336f6f6b2
Create Date: 2026-06-17 14:59:40.281610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df6833f3ea3'
down_revision: Union[str, Sequence[str], None] = 'f51336f6f6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_extension_request', sa.Column('new_deadline', sa.TIMESTAMP(timezone=True), nullable=False))
    op.drop_column('tracker_extension_request', 'requested_days')
    op.drop_column('tracker_task', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_task', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True))
    op.add_column('tracker_extension_request', sa.Column('requested_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tracker_extension_request', 'new_deadline')
    # ### end Alembic commands ###
