"""add_tracker_task_vector

Revision ID: 57517f078f2d
Revises: j1k2l3m4n5o6
Create Date: 2026-06-01 16:36:43.080433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '57517f078f2d'
down_revision: Union[str, Sequence[str], None] = 'j1k2l3m4n5o6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP INDEX IF EXISTS idx_tracker_checklist_task_id")
    op.execute("DROP INDEX IF EXISTS idx_tracker_subtask_checklist_id")
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('tracker_task')]
    if 'task_vector' not in columns:
        op.add_column('tracker_task', sa.Column('task_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    indexes = [idx['name'] for idx in inspector.get_indexes('tracker_task')]
    if 'idx_tracker_task_vector' not in indexes:
        op.create_index('idx_tracker_task_vector', 'tracker_task', ['task_vector'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'task_vector': 'vector_cosine_ops'})
    if 'severity' in columns:
        op.drop_column('tracker_task', 'severity')
    op.execute("DROP INDEX IF EXISTS idx_tracker_task_member_employee_id")
    op.execute("DROP INDEX IF EXISTS idx_tracker_task_member_task_id")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tracker_task_member_task_id'), 'tracker_task_member', ['task_id'], unique=False)
    op.create_index(op.f('idx_tracker_task_member_employee_id'), 'tracker_task_member', ['employee_id'], unique=False)
    op.add_column('tracker_task', sa.Column('severity', sa.VARCHAR(length=10), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False))
    op.drop_index('idx_tracker_task_vector', table_name='tracker_task', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'task_vector': 'vector_cosine_ops'})
    op.drop_column('tracker_task', 'task_vector')
    op.create_index(op.f('idx_tracker_subtask_checklist_id'), 'tracker_subtask', ['checklist_id'], unique=False)
    op.create_index(op.f('idx_tracker_checklist_task_id'), 'tracker_checklist', ['task_id'], unique=False)
    # ### end Alembic commands ###
