"""initial_partner_schema

Revision ID: c45ec8f8ef8e
Revises: 
Create Date: 2026-04-06 12:48:33.359794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c45ec8f8ef8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('department',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_table('holiday',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('holiday_type', sa.String(length=30), server_default='national', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'holiday_date')
    )
    op.create_table('leave_policy',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=30), nullable=False),
    sa.Column('days_per_month', sa.Numeric(precision=5, scale=2), server_default='1', nullable=False),
    sa.Column('max_carry_fwd', sa.Numeric(precision=5, scale=2), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'leave_type')
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_table('employee',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='employee', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('employee', 'admin')", name='check_role'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_table('attendance_session',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('check_in_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('check_out_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('total_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('work_mode', sa.String(length=20), server_default='office', nullable=False),
    sa.Column('is_corrected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('correction_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_out_at IS NULL OR check_out_at > check_in_at', name='chk_checkout_after_checkin'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'session_date', name='uq_session_per_day')
    )
    op.create_index('idx_sess_emp_date', 'attendance_session', ['employee_id', 'session_date'], unique=False)
    op.create_index('idx_sess_org_date', 'attendance_session', ['organization_id', 'session_date'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employee.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_time', 'audit_log', ['created_at'], unique=False)
    op.create_table('employee_leave_balance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('accrued', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('used', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('adjusted', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type', 'year', 'month')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_token_employee_id'), 'refresh_token', ['employee_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_token_id'), 'refresh_token', ['token_id'], unique=True)
    op.create_table('leave_wfh_request',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('linked_session_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rejection_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('to_date >= from_date', name='chk_dates'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_session_id'], ['attendance_session.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employee.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_req_employee', 'leave_wfh_request', ['employee_id'], unique=False)
    op.create_index('idx_req_org_status', 'leave_wfh_request', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_leave_wfh_request_status'), 'leave_wfh_request', ['status'], unique=False)
    op.create_table('task_entry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('hours_logged', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hours_logged > 0 AND hours_logged <= 24', name='chk_hours'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_employee', 'task_entry', ['employee_id'], unique=False)
    op.create_index('idx_tasks_project', 'task_entry', ['project_id'], unique=False)
    op.create_index('idx_tasks_session', 'task_entry', ['session_id'], unique=False)
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_leave_wfh_requests_employee_id', table_name='leave_wfh_requests')
    op.drop_index('ix_leave_wfh_requests_status', table_name='leave_wfh_requests')
    op.drop_table('leave_wfh_requests')
    op.drop_index('ix_holidays_holiday_date', table_name='holidays')
    op.drop_index('ix_holidays_organization_id', table_name='holidays')
    op.drop_table('holidays')
    op.drop_index('ix_refresh_tokens_employee_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_employees_email', table_name='employees')
    op.drop_table('employees')
    op.drop_table('projects')
    op.drop_table('leave_policies')
    op.drop_table('organizations')
    op.drop_index('ix_task_entries_session_id', table_name='task_entries')
    op.drop_table('task_entries')
    op.drop_index('ix_employee_leave_balances_employee_id', table_name='employee_leave_balances')
    op.drop_table('employee_leave_balances')
    op.drop_index('ix_attendance_sessions_employee_id', table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_session_date', table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_table('departments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='departments_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='departments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('attendance_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('check_out_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('work_mode', postgresql.ENUM('office', 'wfh', name='work_mode_enum'), autoincrement=False, nullable=False),
    sa.Column('is_corrected', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('correction_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='attendance_sessions_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='attendance_sessions_pkey'),
    sa.UniqueConstraint('employee_id', 'session_date', name='uq_session_per_day'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_attendance_sessions_session_date', 'attendance_sessions', ['session_date'], unique=False)
    op.create_index('ix_attendance_sessions_employee_id', 'attendance_sessions', ['employee_id'], unique=False)
    op.create_table('employee_leave_balances',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leave_type', postgresql.ENUM('casual', 'comp_off', name='leave_type_enum'), autoincrement=False, nullable=False),
    sa.Column('opening_balance', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('accrued', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('used', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('adjusted', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('closing_balance', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_leave_balances_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='employee_leave_balances_pkey'),
    sa.UniqueConstraint('employee_id', 'year', 'month', 'leave_type', name='uq_balance_per_month')
    )
    op.create_index('ix_employee_leave_balances_employee_id', 'employee_leave_balances', ['employee_id'], unique=False)
    op.create_table('task_entries',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hours', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='task_entries_project_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], name='task_entries_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='task_entries_pkey')
    )
    op.create_index('ix_task_entries_session_id', 'task_entries', ['session_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('leave_policies',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('leave_type', postgresql.ENUM('casual', 'comp_off', name='leave_type_enum'), autoincrement=False, nullable=False),
    sa.Column('accrual_per_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_carry_forward', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='leave_policies_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='leave_policies_pkey'),
    sa.UniqueConstraint('organization_id', 'leave_type', name='uq_policy_per_type')
    )
    op.create_table('projects',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='projects_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='projects_pkey')
    )
    op.create_table('employees',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('employee', 'admin', name='employee_role_enum'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('auth_provider', sa.VARCHAR(length=20), server_default=sa.text("'google'::character varying"), autoincrement=False, nullable=False, comment='Authentication provider: google or local'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='employees_department_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='employees_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='employees_pkey'),
    sa.UniqueConstraint('google_id', name='employees_google_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_employees_email', 'employees', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='refresh_tokens_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey'),
    sa.UniqueConstraint('token_hash', name='refresh_tokens_token_hash_key')
    )
    op.create_index('ix_refresh_tokens_employee_id', 'refresh_tokens', ['employee_id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('holiday_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='holidays_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='holidays_pkey')
    )
    op.create_index('ix_holidays_organization_id', 'holidays', ['organization_id'], unique=False)
    op.create_index('ix_holidays_holiday_date', 'holidays', ['holiday_date'], unique=False)
    op.create_table('leave_wfh_requests',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('request_type', postgresql.ENUM('leave', 'wfh', 'missing_time', 'comp_off', name='request_type_enum'), autoincrement=False, nullable=False),
    sa.Column('from_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('to_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('days_taken', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='request_status_enum'), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('review_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('linked_session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='leave_wfh_requests_employee_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_session_id'], ['attendance_sessions.id'], name='leave_wfh_requests_linked_session_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.id'], name='leave_wfh_requests_reviewed_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='leave_wfh_requests_pkey')
    )
    op.create_index('ix_leave_wfh_requests_status', 'leave_wfh_requests', ['status'], unique=False)
    op.create_index('ix_leave_wfh_requests_employee_id', 'leave_wfh_requests', ['employee_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], name='audit_logs_actor_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.drop_index('idx_tasks_session', table_name='task_entry')
    op.drop_index('idx_tasks_project', table_name='task_entry')
    op.drop_index('idx_tasks_employee', table_name='task_entry')
    op.drop_table('task_entry')
    op.drop_index(op.f('ix_leave_wfh_request_status'), table_name='leave_wfh_request')
    op.drop_index('idx_req_org_status', table_name='leave_wfh_request')
    op.drop_index('idx_req_employee', table_name='leave_wfh_request')
    op.drop_table('leave_wfh_request')
    op.drop_index(op.f('ix_refresh_token_token_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_employee_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_table('employee_leave_balance')
    op.drop_index('idx_audit_time', table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_sess_org_date', table_name='attendance_session')
    op.drop_index('idx_sess_emp_date', table_name='attendance_session')
    op.drop_table('attendance_session')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    op.drop_table('project')
    op.drop_table('leave_policy')
    op.drop_table('holiday')
    op.drop_table('department')
    op.drop_table('organization')
    # ### end Alembic commands ###
