"""add_tracker_module

Revision ID: f69c5e1f6256
Revises: e7f1a2b3c4d5
Create Date: 2026-05-20 12:38:19.562633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69c5e1f6256'
down_revision: Union[str, Sequence[str], None] = 'e7f1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_task',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('request_type', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.String(length=10), server_default='medium', nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending_approval', nullable=False),
    sa.Column('deadline', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'urgent')", name='chk_tracker_task_priority'),
    sa.CheckConstraint("request_type IN ('bug', 'task')", name='chk_tracker_task_request_type'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='chk_tracker_task_severity'),
    sa.CheckConstraint("status IN ('pending_approval','assigned','todo','in_progress','blocked','testing','completed','rejected')", name='chk_tracker_task_status'),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracker_task_assigned_to', 'tracker_task', ['assigned_to'], unique=False)
    op.create_index('idx_tracker_task_created_by', 'tracker_task', ['created_by'], unique=False)
    op.create_index('idx_tracker_task_deadline', 'tracker_task', ['deadline'], unique=False)
    op.create_index('idx_tracker_task_status', 'tracker_task', ['status'], unique=False)
    op.create_table('tracker_activity_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tracker_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracker_activity_task_id', 'tracker_activity_log', ['task_id'], unique=False)
    op.create_table('tracker_attachment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("file_type IN ('image','video','document','pdf')", name='chk_tracker_attachment_file_type'),
    sa.ForeignKeyConstraint(['task_id'], ['tracker_task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracker_comment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tracker_task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracker_extension_request',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('requested_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='chk_tracker_ext_status'),
    sa.ForeignKeyConstraint(['requested_by'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tracker_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracker_notification',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tracker_task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracker_notif_user_unread', 'tracker_notification', ['user_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tracker_notif_user_unread', table_name='tracker_notification')
    op.drop_table('tracker_notification')
    op.drop_table('tracker_extension_request')
    op.drop_table('tracker_comment')
    op.drop_table('tracker_attachment')
    op.drop_index('idx_tracker_activity_task_id', table_name='tracker_activity_log')
    op.drop_table('tracker_activity_log')
    op.drop_index('idx_tracker_task_status', table_name='tracker_task')
    op.drop_index('idx_tracker_task_deadline', table_name='tracker_task')
    op.drop_index('idx_tracker_task_created_by', table_name='tracker_task')
    op.drop_index('idx_tracker_task_assigned_to', table_name='tracker_task')
    op.drop_table('tracker_task')
    # ### end Alembic commands ###
