"""
app/models/organization.py — Organization Database Model
=========================================================
Defines the `organization` table — the top-level tenant record.

Non-technical summary:
----------------------
An "organization" is the company using this HRMS. Every employee,
department, project, holiday, and leave policy belongs to one organization.
This design allows the system to support multiple companies in the future
(multi-tenancy), though currently only one organization is expected.

Table: organization
Columns:
  - id         : Unique identifier (UUID, auto-generated by the database)
  - name       : Full company name (e.g. "Acme Corp")
  - slug       : URL-friendly short name (e.g. "acme-corp"), must be unique
  - created_at : When the record was created
  - updated_at : When the record was last modified
"""

import uuid
from datetime import datetime

from sqlalchemy import String, TIMESTAMP, text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models import Base


class Organization(Base):
    """
    SQLAlchemy ORM model for the `organization` table.

    Represents a single company/tenant. All other records (employees,
    projects, holidays, etc.) reference this via organization_id.
    """
    __tablename__ = "organization"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),  # DB generates UUID automatically
    )

    # Full display name of the company
    name: Mapped[str] = mapped_column(String(255), nullable=False)

    # Short URL-safe identifier — must be unique across all organizations
    slug: Mapped[str] = mapped_column(String(100), nullable=False, unique=True)

    # Automatically set to the current timestamp when the row is inserted
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=text("now()"),
        nullable=False,
    )

    # Automatically updated whenever the row is modified
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=text("now()"),
        onupdate=text("now()"),
        nullable=False,
    )
